version: 0.1

phases:
  install:
    commands:
      - echo Installation starting
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging files...
      - cd dist && zip -r ../dist.zip .
artifacts:
  files:
    - dist.zip
