const transfer = '/transfer'
const home = '/'
const pets = '/pets'
const petDetails = '/pet-details/:id'
const news = '/news/:id'
const calendar = '/calendar'
const account = '/account'
const linkExpired = '/activation-link-expired'
const firstSignIn = '/first-sign-in'
const accountPassword = '/account-password'
const signIn = '/sign-in'
const help = '/help'
const helpInfo = '/help-info'
const volunteer = '/volunteer'
const resetPassword = '/reset-password'

export default { transfer, home, news, pets, petDetails, calendar, account, accountPassword, linkExpired, firstSignIn, signIn, help, helpInfo, volunteer, resetPassword }
