module.exports = {
  'test PetDetails.vue': function (browser) {
    const devServer = browser.globals.devServerURL
      browser
        .url(devServer)
        .waitForElementVisible('#app', 1000)
        .waitForElementVisible('nav', 1000)
        .setValue('input[type=email]', 'TOZ_user0.email@gmail.com')
        .setValue('input[type=password]', 'TOZ_name_0')
        .waitForElementVisible('button[type=submit]', 1000)
        .click('button[type=submit]')
        .pause(1000)
        .refresh()
        .pause(2000)
        .waitForElementVisible('a[href="#/pets"]', 2000)
        .click('a[href="#/pets"]')
        .pause(1000)
        .assert.elementPresent('.container')
        .click('a[href="#/pet-details/d0d251e9-51eb-4133-a303-49231319186c"]')
        .pause(1000)
        .assert.elementPresent('#petDetails')
        .assert.elementPresent('#pet-container')
        .assert.elementPresent('.swiper-wrapper')
        .assert.elementCount('.swiper-slide', 10)
        .assert.elementPresent('.petInfo')
        .assert.elementPresent('ul')
        .assert.elementCount('.petInfo > ul > li',4)
        .assert.containsText('.petInfo > ul > li:nth-child(1) > div > h6', 'name_0')
        .assert.containsText('.petInfo > ul > li:nth-child(1) > div > span', 'Imię')
        .assert.containsText('.petInfo > ul > li:nth-child(2) > div:nth-child(1) > h6', 'DOG')
        .assert.containsText('.petInfo > ul > li:nth-child(2) > div:nth-child(1) > span', 'Typ')
        .assert.containsText('.petInfo > ul > li:nth-child(2) > div:nth-child(2) > h6', 'MALE')
        .assert.containsText('.petInfo > ul > li:nth-child(2) > div:nth-child(2) > span', 'Płeć')
        .assert.containsText('.petInfo > ul > li:nth-child(3) > div > h6', '12.05.2017')
        .assert.containsText('.petInfo > ul > li:nth-child(3) > div > span', 'Data dodania')
        .assert.containsText('.petInfo > ul > li:nth-child(4) > div > p', 'description_0')
        .assert.elementPresent('button.helpLink')
        .assert.containsText('button.helpLink', 'WSPOMÓŻ TEGO ZWIERZAKA')
        .click('button.helpLink')
        .waitForElementVisible('.transfer', 1000)
        .assert.containsText('.transfer > h1', 'Dane do przelewu')
        .assert.elementPresent('.transfer > a.router-link-active')
        .assert.containsText('.transfer > a.router-link-active', 'Powrót do strony głównej')
        .click('.transfer > a[href="#/"]')
        .end()
  }
}
